//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GiftCardAngular.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiftCard
    {
        public GiftCard()
        {
            this.Transactions = new HashSet<Transaction>();
        }
    
        public int GiftCardId { get; set; }
        public string BarCode { get; set; }
        public System.DateTime DatePurchased { get; set; }
        public string Comments { get; set; }
        public byte[] TimeStamp { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}
